(define (main)
    (let ((llista (read)))
        (display (car llista))      
        (newline)
        (display (cdr llista))      
        (newline)
        (display (cons 0 llista))   ; esperat: '(0 1 2 3 4 5)
        (newline)
        (display (null? '()))      
        (newline)
        (display (null? llista))   
        (newline)))
